export class TrainingDemand {
  id?: number;
  orgId?: number;
  orgName?: string;
  year?: string;
  classTrain?: number;
  programGroupId?: number;
  programId?: number;
  phanLoai?: string;
  tinhChatId?: number;
  linhVucDaoTao?: string;
  doiTuongHocVien?: string;
  chiPhiHocVien?: number;
  totalChiPhi?: number;
  thoiLuong?: number;
  tuGio?:Date;
  denGio?:Date;
  tuNgay?:Date;
  denNgay?:Date;
  thoiGianHocId?:number;
  trongGioHc?:number;
  ngoaiGioHc?:number;
  coThiLai?:boolean;
  coBoiHoan?:boolean;
  noiDungDaoTao?:string;
  trungTamId?:number;
  giangVienId?:number;
  chiPhiDk?:number;
  statusId?:number;
  mucTieu?:string;
  diaDiemToChuc?:string;
  signId?:number;
  emailSign?:string;
  phoneNumber?:string;
  ngaygui?:Date;
  fileName?:string;
  note?:string;
  trongKeHoach?:boolean;
  signName?:string;
}