import { Navigation } from "../_models/index";

export const navigation: Navigation[] = [
  {
    id: "cms_organize",
    title: "Tổ chức",
    translate: "Tổ chức",
    type: "module",
    icon: "org",
    url: "/hrms/organize",
    root: true,
    children: [
      
      {
        id: "organize_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/organize/business",
        children: [
          {
            id: "orgchart",
            title: "Cây sơ đồ tổ chức",
            translate: "Cây sơ đồ tổ chức",
            type: "item",
            url: "/hrms/profile/setting/orgchart",
            exactMatch: true,
            children: [],
          },
          {
            id: "org_dashboard",
            title: "Tổng quan công việc",
            translate: "Tổng quan công việc",
            type: "item",
            url: "/hrms/organize/dashboarddetail/dashboardposition",
            exactMatch: true,
            children: []
          },
          {
            id: "org_struct",
            title: "Cơ cấu tổ chức",
            translate: "Cơ cấu tổ chức",
            type: "item",
            url: "/hrms/organize/business/organization-struct",
            exactMatch: true,
            children: [],
          },
          {
            id: "job",
            title: "Công việc",
            translate: "Công việc",
            type: "item",
            url: "/hrms/organize/business/job",
            exactMatch: true,
            children: [],
          },
          {
            id: "org_position",
            title: "Vị trí",
            translate: "Vị trí",
            type: "item",
            url: "/hrms/organize/business/position",
            exactMatch: true,
            children: [],
          },

          {
            id: "organization",
            title: "Khai báo cơ cấu tổ chức",
            translate: "Khai báo cơ cấu tổ chức",
            type: "item",
            url: "/hrms/organize/business/organization",
            exactMatch: true,
            children: [],
          },

        ],
      },
      {
        id: "organize_report",
        title: "Báo cáo",
        translate: "Báo cáo",
        type: "group",
        icon: "file",
        url: "/hrms/organize/report",
        children: [
          {
            id: "org_report",
            title: "Báo cáo biểu đồ",
            translate: "Báo cáo biểu đồ",
            type: "item",
            url: "/hrms/organize/report/reports",
            exactMatch: true,
            children: [],
          },
        ],
      },
      {
        id: "cms_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/organize/list",
        children: [
          {
            id: "job-band",
            title: "Cấp bậc",
            translate: "Cấp bậc",
            type: "item",
            url: "/hrms/organize/list/job-band",
            exactMatch: true,
            children: [],
          },

          {
            id: "companyinfo",
            title: "Thông tin công ty",
            translate: "Thông tin công ty",
            type: "item",
            url: "/hrms/organize/list/companyinfo",
            exactMatch: true,
            children: [],
          },
          {
            id: "title",
            title: "Chức danh",
            translate: "Chức danh",
            type: "item",
            url: "/hrms/organize/list/title",
            exactMatch: true,
            children: [],
          },
          {
            id: "positionorg",
            title: "Vị trí công việc cho bộ phận",
            translate: "Vị trí công việc cho bộ phận",
            type: "item",
            url: "/hrms/organize/list/positionorg",
            exactMatch: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "smp_recrui",
    title: "Tuyển dụng",
    translate: "Tuyển dụng",
    type: "module",
    icon: "recruis",
    url: "",
    root: true,
    children: [
    
      {
        id: "cms_app_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/recruiment/business",
        children: [
          {
            id: "dashboard",
            title: "Dashboard",
            translate: "Dashboard",
            type: "item",
            url: "/hrms/recruiment/business/dashboard",
            exactMatch: true, children: [],
          },
          {
            id: "quanlydinhbien",
            title: "Định biên nhân sự",
            translate: "Định biên nhân sự",
            type: "item",
            url: "/hrms/recruiment/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "nhucautuyendung",
            title: "Nhu cầu tuyển dụng",
            translate: "Nhu cầu tuyển dụng",
            type: "item",
            url: "/hrms/recruiment/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "quanlytuyendung",
            title: "Kế hoạch tuyển dụng",
            translate: "Kế hoạch tuyển dụng",
            type: "item",
            url: "/hrms/profile/business/recruitmentplan",
            exactMatch: true, children: [],
          },
          {
            id: "dexuatluong",
            title: "Đợt tuyển dụng",
            translate: "Đợt tuyển dụng",
            type: "item",
            url: "/hrms/recruiment/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "damphanluong",
            title: "Tổ chức tuyển dụng theo đợt",
            translate: "Tổ chức tuyển dụng theo đợt",
            type: "item",
            url: "/hrms/recruiment/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "chiphituyendung",
            title: "Quản lý chi phí tuyển dụng",
            translate: "Quản lý chi phí tuyển dụng",
            type: "item",
            url: "/hrms/recruiment/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "dexuat",
            title: "Đề xuất lương",
            translate: "Đề xuất lương",
            type: "item",
            url: "/hrms/recruiment/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "damphan",
            title: "Đàm phán lương và hướng dẫn onboard",
            translate: "Đàm phán lương và hướng dẫn onboard",
            type: "item",
            url: "/hrms/recruiment/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "quanlynguonungvien",
            title: "Quản lý nguồn ứng viên",
            translate: "Quản lý nguồn ứng viên",
            type: "item",
            url: "/hrms/recruiment/list/insarising",
            exactMatch: true, children: [],
          },
          
          
          
          
        ]
      },
      {
        id: "cms_app_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/recruiment/list",
        children: [
          
          
          {
            id: "monthituyen",
            title: "Môn thi tuyển",
            translate: "Môn thi tuyển",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          
          
          
        ]
      },
    ]
  },
  {
    
    id: "cms_profile",
    title: "Hồ sơ",
    translate: "Hồ sơ",
    type: "module",
    icon: "hu",
    url: "/hrms/profile",
    root: true,
    children: [
      {
        id: "cms_staff",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/profile/business",
        children: [
          {
            id: "staff_profile",
            title: "Hồ sơ nhân viên",
            translate: "NAV.STAFF_LIST.STAFFPROFILE",
            type: "item",
            url: "/hrms/profile/business/staffprofile",
            exactMatch: true,
            children: [],
          },
          {
            id: "contact_profile",
            title: "Tra cứ thông tin nhân viên",
            translate: "NAV.STAFF_LIST.CONTACTPROFILE",
            type: "item",
            url: "/hrms/profile/business/contactprofile",
            exactMatch: true,
            children: [],
          },
          {
            id: "decision",
            title: "Quản lý quyết định",
            translate: "Quản lý quyết định",
            type: "item",
            url: "/hrms/profile/business/decision",
            exactMatch: true,
            children: [],
          },
          {
            id: "contractinfor",
            title: "Quản lý hợp đồng",
            translate: "Quản lý hợp đồng",
            type: "item",
            url: "/hrms/profile/business/contractinfor",
            exactMatch: true,
            children: [],
          },
          {
            id: "concurrentlymng",
            title: "Quản lý kiêm nhiệm",
            translate: "Quản lý kiêm nhiệm",
            type: "item",
            url: "/hrms/profile/business/concurrentlymng",
            exactMatch: true,
            children: [],
          },
          {
            id: "commend",
            title: "Quản lý khen thưởng",
            translate: "Quản lý khen thưởng",
            type: "item",
            url: "/hrms/profile/business/commend",
            exactMatch: true,
            children: [],
          },
          {
            id: "discipline",
            title: "Quản lý kỷ luật",
            translate: "Quản lý kỷ luật",
            type: "item",
            url: "/hrms/profile/business/discipline",
            exactMatch: true,
            children: [],
          },
          {
            id: "leavejob",
            title: "Quản lý nghỉ việc",
            translate: "Quản lý nghỉ việc",
            type: "item",
            url: "/hrms/profile/business/leavejob",
            exactMatch: true,
            children: [],
          },
          {
            id: "workingbefore",
            title: "Quá trình công tác trước đây",
            translate: "Quá trình công tác trước đây",
            type: "item",
            url: "/hrms/profile/business/workingbefore",
            exactMatch: true,
            children: [],
          },
          {
            id: "trainingbefore",
            title: "Quá trình đào tạo trước đây",
            translate: "Quá trình đào tạo trước đây",
            type: "item",
            url: "/hrms/profile/business/trainingbefore",
            exactMatch: true,
            children: [],
          },
          {
            id: "welfarecal",
            title: "Quản lý phúc lợi",
            translate: "Quản lý phúc lợi",
            type: "item",
            url: "/hrms/profile/business/welfarecal",
            exactMatch: true,
            children: [],
          },
          {
            id: "welfaremng",
            title: "Quản lý phúc lợi bổ sung",
            translate: "Quản lý phúc lợi bổ sung",
            type: "item",
            url: "/hrms/profile/business/welfaremng",
            exactMatch: true,
            children: [],
          },
          {
            id: "leavejobsettlement",
            title: "Quản lý quyết toán nghỉ việc",
            translate: "Quản lý quyết toán nghỉ việc",
            type: "item",
            url: "/hrms/profile/business/leavejobsettlement",
            exactMatch: true,
            children: [],
          },
          {
            id: "staffprofile-change",
            title: "Thông tin hồ sơ",
            translate: "Thông tin hồ sơ",
            type: "item",
            url: "/hrms/profile/business/staffprofile-change",
            exactMatch: true,
            children: [],
          },
          {
            id: "family-change",
            title: "Thông tin Gia cảnh",
            translate: "Thông tin Gia cảnh",
            type: "item",
            url: "/hrms/profile/business/family-change",
            exactMatch: true,
            children: [],
          },
          // {
          //   id: "angular-tree-grid",
          //   title: "Cơ cấu tổ chức",
          //   translate: "Cơ cấu tổ chức",
          //   type: "item",
          //   url: "/hrms/profile/business/angular-tree-grid",
          //   exactMatch: true,
          // },
          // {
          //   id: "cms_timekeepingreport",
          //   title: "Báo cáo chấm công",
          //   translate: "NAV.STAFF_LIST.TIMEKEEPINGREPORT",
          //   type: "group",
          //   exactMatch: true,
          //   children: [
          //     {
          //       id: "cms_member_report",
          //       title: "Danh sách nhân viên đi muộn về sớm và nghỉ",
          //       translate: "NAV.STAFF_LIST.MEMBERREPORT",
          //       type: "item",
          //       url: "/hrms/staff/memberreport",
          //       exactMatch: true,
          //     },
          //     {
          //       id: "cms_total_report",
          //       title: "Báo cáo tổng hợp số ngày nghỉ của nhân viên",
          //       translate: "NAV.STAFF_LIST.TOTALREPORT",
          //       type: "item",
          //       url: "/hrms/staff/totalreport",
          //       exactMatch: true,
          //     },
          //   ],
          // },
        ],
      },
      {
        id: "cms_profile_report",
        title: "Báo cáo",
        translate: "Báo cáo",
        type: "group",
        icon: "file",
        url: "/hrms/profile/business",
        children: [
          {
            id: "report-dynamic",
            title: "Báo cáo tùy chỉnh",
            translate: "Báo cáo tùy chỉnh",
            type: "item",
            url: "/hrms/profile/business/report-dynamic",
            exactMatch: true,
            children: [],
          }
        ],
      },
      {
        id: "cms_system",
        title: "Thiết lập",
        translate: "Thiết lập",
        type: "group",
        icon: "gear",
        url: "/hrms/profile/setting",
        children: [
          
          {
            id: "allowanseemployee",
            title: "Phụ cấp nhân viên",
            translate: "Phụ cấp nhân viên",
            type: "item",
            url: "/hrms/profile/list/allowanseemployee",
            exactMatch: true,
            children: [],
          },
          {
            id: "cms_pospaper",
            title: "Giấy tờ theo chức vụ",
            translate: "Giấy tờ theo chức vụ",
            type: "item",
            url: "/hrms/profile/setting/pospaper",
            exactMatch: true,
            children: [],
          },
          {
            id: "cms-app-decisioncreate",
            title: "Thiết lập quy tắc sinh số quyết định",
            translate: "Thiết lập quy tắc sinh số quyết định",
            type: "item",
            url: "/hrms/profile/setting/decisioncreate",
            exactMatch: true,
            children: [],
          },
        ],
      },
      {
        id: "cms_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/profile/list",
        children: [
          {
            id: "position_group",
            title: "Nhóm chức danh",
            translate: "Nhóm chức danh",
            type: "item",
            url: "/hrms/profile/list/groupposition",
            exactMatch: true,
            children: [],
          },
          {
            id: "contracttype",
            title: "Loại hợp đồng",
            translate: "Loại hợp đồng",
            type: "item",
            url: "/hrms/profile/list/contracttype",
            exactMatch: true,
            children: [],
          },
          {
            id: "welfare",
            title: "Phúc lợi",
            translate: "Phúc lợi",
            type: "item",
            url: "/hrms/profile/list/welfare",
            exactMatch: true,
            children: [],
          },
          {
            id: "allowance",
            title: "Phụ cấp",
            translate: "Phụ cấp",
            type: "item",
            url: "/hrms/profile/list/allowance",
            exactMatch: true,
            children: [],
          },

          {
            id: "salaryscale",
            title: "Thang lương",
            translate: "Thang lương",
            type: "item",
            url: "/hrms/profile/list/salaryscale",
            exactMatch: true,
            children: [],
          },
          {
            id: "salaryrank",
            title: "Ngạch lương",
            translate: "Ngạch lương",
            type: "item",
            url: "/hrms/profile/list/salaryrank",
            exactMatch: true,
            children: [],
          },
          {
            id: "salarylevel",
            title: "Bậc lương",
            translate: "Bậc lương",
            type: "item",
            url: "/hrms/profile/list/salarylevel",
            exactMatch: true,
            children: [],
          },
          {
            id: "salarytype",
            title: "Bảng lương",
            translate: "Bảng lương",
            type: "item",
            url: "/hrms/profile/list/salarytype",
            exactMatch: true,
            children: [],
          },
          {
            id: "salarysample",
            title: "Thang bảng lương",
            translate: "Thang bảng lương",
            type: "item",
            url: "/hrms/profile/list/salarysample",
            exactMatch: true,
            children: [],
          },
          {
            id: "bank",
            title: "Ngân hàng",
            translate: "Ngân hàng",
            type: "item",
            url: "/hrms/profile/list/bank",
            exactMatch: true,
            children: [],
          },
          {
            id: "bankbranch",
            title: "Nhánh ngân hàng",
            translate: "Nhánh ngân hàng",
            type: "item",
            url: "/hrms/profile/list/bankbranch",
            exactMatch: true,
            children: [],
          },
          {
            id: "otherlist",
            title: "Tham số hệ thống",
            translate: "Tham số hệ thống",
            type: "item",
            url: "/hrms/profile/list/otherlist",
            exactMatch: true,
            children: [],
          },

          // {
          //   id: "job",
          //   title: "Danh mục công việc",
          //   translate: "Danh mục công việc",
          //   type: "item",
          //   url: "/hrms/profile/list/job",
          //   exactMatch: true,
          // }
        ],
      },
      
      
    ],
  },
  {
    id: "cms_insurance",
    title: "Bảo hiểm",
    translate: "Bảo hiểm",
    type: "module",
    icon: "ins",
    url: "/hrms/profile/business/inschange",
    root: true,
    children: [
      {
        id: "cms_bus",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/profile/business",
        children: [
          {
            id: "ins_arising",
            title: "Khai báo đóng mới bảo hiểm",
            translate: "Khai báo đóng mới bảo hiểm",
            type: "item",
            url: "/hrms/profile/business/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "ins_change",
            title: "Biến động bảo hiểm",
            translate: "Biến động bảo hiểm",
            type: "item",
            url: "/hrms/profile/business/inschange",
            exactMatch: true, children: [],
          },
          {
            id: "ins_information",
            title: "Thông tin bảo hiểm",
            translate: "Thông tin bảo hiểm",
            type: "item",
            url: "/hrms/profile/business/insinformation",
            exactMatch: true, children: [],
          },
          {
            id: "insregimemng",
            title: "Quản lý hưởng chế độ bảo hiểm",
            translate: "Quản lý hưởng chế độ bảo hiểm",
            type: "item",
            url: "/hrms/profile/business/insregimemng",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/profile/list",
        children: [
          {
            id: "insspecified",
            title: "Quy định mức đóng bảo hiểm",
            translate: "Quy định mức đóng bảo hiểm",
            type: "item",
            url: "/hrms/profile/list/insspecified",
            exactMatch: true,
            children: [],
          },
          {
            id: "insregimetype",
            title: "Chế độ bảo hiểm",
            translate: "Chế độ bảo hiểm",
            type: "item",
            url: "/hrms/profile/list/insregimetype",
            exactMatch: true,
            children: [],
          },



        ],
      },
      
    ],
  },

  {
    id: "smp_train",
    title: "Đào tạo",
    translate: "Đào tạo",
    type: "module",
    icon: "trains",
    url: "",
    root: true,
    children: [
      {
        id: "smp_train_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/train/business",
        children: [
          
          {
            id: "khaibaonhucaudaotaonam",
            title: "Kế hoạch đào tạo",
            translate: "Kế hoạch đào tạo",
            type: "item",
            url: "/hrms/profile/business/trainingdemand",
            exactMatch: true, children: [],
          },
          {
            id: "tochucdaotao",
            title: "Tổ chức đào tạo",
            translate: "Tổ chức đào tạo",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          
          {
            id: "quanlyboihoandaotao",
            title: "Bồi hoàn đào tạo",
            translate: "Bồi hoàn đào tạo",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },

          {
            id: "employeetrain",
            title: "Hồ sơ đào tạo",
            translate: "Hồ sơ đào tạo",
            type: "item",
            url: "/hrms/profile/business/employeetrain",
            exactMatch: true, children: [],
          },
          
          
        ]
      },
      
      {
        id: "smp_train_setting",
        title: "Thiết lập",
        translate: "Thiết lập",
        type: "group",
        icon: "gear",
        url: "/hrms/train/business",
        children: [
          
          {
            id: "khoadaotao",
            title: "Khóa đào tạo theo công việc",
            translate: "Khóa đào tạo theo công việc",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          
          
          
        ]
      },
      {
        id: "smp_train_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/train/business",
        children: [
          
          {
            id: "chungchi",
            title: "Chứng chỉ",
            translate: "Chứng chỉ",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "nhomchuongtrinh",
            title: "Nhóm chương trình",
            translate: "Nhóm chương trình",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "khoahoc",
            title: "Khóa học",
            translate: "Khóa học",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "trungtam",
            title: "Trung tâm",
            translate: "Trung tâm",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "giangvien",
            title: "Giảng viên",
            translate: "Giảng viên",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "camket",
            title: "Cam kết sau đào tạo",
            translate: "Cam kết sau đào tạo",
            type: "item",
            url: "/hrms/train/list/insarising",
            exactMatch: true, children: [],
          },
          
        ]
      },
      
    ]
  },

  {
    id: "smp_perfom",
    title: "Đánh giá",
    translate: "Đánh giá",
    type: "module",
    icon: "perfom",
    url: "",
    root: true,
    children: [
      {
        id: "cms_app_perfom_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/perfom/business",
        children: [
          {
            id: "cms_app_perfom_business_dashboard",
            title: "Dashboard",
            translate: "Dashboard",
            type: "item",
            url: "/hrms/perfomance/business/dashboard",
            exactMatch: true, children: [],
          },
          {
            id: "canhantudanhgia",
            title: "Cá nhân tự đánh giá",
            translate: "Cá nhân tự đánh giá",
            type: "item",
            url: "/hrms/perfom/business/competencyframe",
            exactMatch: true, children: [],
          },
          {
            id: "quanlydanhgia",
            title: "Quản lý đánh giá",
            translate: "Quản lý đánh giá",
            type: "item",
            url: "/hrms/perfom/business/competencyframe",
            exactMatch: true, children: [],
          },
          {
            id: "tonghop",
            title: "Tổng hợp kết quả đánh giá theo kỳ",
            translate: "Tổng hợp kết quả đánh giá theo kỳ",
            type: "item",
            url: "/hrms/perfom/business/competencyframe",
            exactMatch: true, children: [],
          },
          
          
          
        ]
      },
      {
        id: "cms_app_perfom_setting",
        title: "Thiết lập",
        translate: "Thiết lập",
        type: "group",
        icon: "gear",
        url: "/hrms/perfom/setting",
        children: [
          
          {
            id: "leuleu",
            title: "Tiêu chí đánh giá theo vị trí công việc",
            translate: "Tiêu chí đánh giá theo vị trí công việc",
            type: "item",
            url: "/hrms/perfom/setting/competencyframe",
            exactMatch: true, children: [],
          },
          
          
          
          
        ]
      },
      
      {
        id: "cms_app_perfom_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/perfom/list",
        children: [
          
          {
            id: "nhomtieuchi",
            title: "Nhóm tiêu chí",
            translate: "Nhóm tiêu chí",
            type: "item",
            url: "/hrms/perfom/list/competencyframe",
            exactMatch: true, children: [],
          },
          {
            id: "tieuchi",
            title: "Tiêu chí",
            translate: "Tiêu chí",
            type: "item",
            url: "/hrms/perfom/list/competencyframe",
            exactMatch: true, children: [],
          },
          {
            id: "kydanhgia",
            title: "Kỳ đánh giá",
            translate: "Kỳ đánh giá",
            type: "item",
            url: "/hrms/perfom/list/competencyframe",
            exactMatch: true, children: [],
          },
          
          
          
        ]
      },
    ]
  },
  {
    id: "smp_star",
    title: "Khung năng lực",
    translate: "Khung năng lực",
    type: "module",
    icon: "stars",
    url: "",
    root: true,
    children: [
      {
        id: "cms_app_star_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/stars/business",
        children: [
          {
            id: "cms_app_perfom_business_dashboard",
            title: "So sánh năng lực",
            translate: "So sánh năng lực",
            type: "item",
            url: "/hrms/perfomance/business/dashboard",
            exactMatch: true, children: [],
          },
          {
            id: "CompetencyTranslate",
            title: "Từ điển năng lực",
            translate: "Từ điển năng lực",
            type: "item",
            url: "/hrms/profile/list/competencylevellist",
            exactMatch: true, children: [],
          },
          {
            id: "danhgianangluc",
            title: "Đánh giá năng lực nhân viên",
            translate: "Đánh giá năng lực nhân viên",
            type: "item",
            url: "/hrms/stars/list/insarising",
            exactMatch: true, children: [],
          },
          {
            id: "timkiemnhanvien",
            title: "Hồ sơ năng lực",
            translate: "Hồ sơ năng lực",
            type: "item",
            url: "/hrms/stars/list/insarising",
            exactMatch: true, children: [],
          },
          
          
          
        ]
      },
      {
        id: "cms_app_star_setting",
        title: "Thiết lập",
        translate: "Thiết lập",
        type: "group",
        icon: "gear",
        url: "/hrms/profile/list",
        children: [
          {
            id: "capdodanhgia",
            title: "Cấp độ năng lực",
            translate: "Cấp độ năng lực",
            type: "item",
            url: "/hrms/profile/list/competencylevel",
            exactMatch: true, children: [],
          },
          {
            id: "compesetposition",
            title: "Chuẩn năng lực cho từng vị trí",
            translate: "Chuẩn năng lực cho từng vị trí",
            type: "item",
            url: "/hrms/profile/list/compesetposition",
            exactMatch: true, children: [],
          },

        ]
      },
      {
        id: "cms_app_star_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/profile/list",
        children: [
          
          {
            id: "nangluc",
            title: "Năng lực",
            translate: "Năng lực",
            type: "item",
            url: "/hrms/profile/list/competencyframe",
            exactMatch: true, children: [],
          },
          {
            id: "kydanhgianl",
            title: "Kỳ đánh giá năng lực",
            translate: "Kỳ đánh giá năng lực",
            type: "item",
            url: "/hrms/stars/list/insarising",
            exactMatch: true, children: [],
          },
          
         
          
        ]
      },
      
      
    ]
  },
  {
    id: "cms_attendance",
    title: "Chấm công",
    translate: "Chấm công",
    type: "module",
    icon: "att",
    url: "/hrms/attendance/business/shiftsort",
    root: true,
    children: [
      {
        id: "cms_attendance_bus",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/attendance/business",
        children: [
          {
            id: "swipedata",
            title: "Quản lý dữ liệu chấm công",
            translate: "Quản lý dữ liệu chấm công",
            type: "item",
            url: "/hrms/attendance/business/swipedata",
            exactMatch: true, children: [],
          },
          {
            id: "shift_sort",
            title: "Quản lý ca làm việc",
            translate: "Quản lý ca làm việc",
            type: "item",
            url: "/hrms/attendance/business/shiftsort",
            exactMatch: true, children: [],
          },
          // {
          //   id: "duty_sort",
          //   title: "Xếp ca Trực",
          //   translate: "Xếp ca Trực",
          //   type: "item",
          //   url: "/hrms/attendance/business/dutyscheduled",
          //   exactMatch: true, children: [],
          // },
          

          {
            id: "time_late_early",
            title: "Quản lý đi trễ, về sớm",
            translate: "Quản lý đi trễ, về sớm",
            type: "item",
            url: "/hrms/attendance/business/timelateearly",
            exactMatch: true, children: [],
          },
          {
            id: "register_off",
            title: "Quản lý đăng ký nghỉ",
            translate: "Quản lý đăng ký nghỉ",
            type: "item",
            url: "/hrms/attendance/business/registeroff",
            exactMatch: true, children: [],
          },
          {
            id: "overtime",
            title: "Quản lý đăng ký làm thêm giờ",
            translate: "Quản lý đăng ký làm thêm giờ",
            type: "item",
            url: "/hrms/attendance/business/overtime",
            exactMatch: true, children: [],
          },
          {
            id: "timesheet",
            title: "Bảng công",
            translate: "Bảng công",
            type: "item",
            url: "/hrms/attendance/business/timesheet",
            exactMatch: true, children: [],
          },
          {
            id: "takeleave",
            title: "Quản lý phép năm",
            translate: "Quản lý phép năm",
            type: "item",
            url: "/hrms/attendance/business/takeleave",
            exactMatch: true, children: [],
          },
          {
            id: "declareleave",
            title: "Quản lý phép năm điều chỉnh, bổ sung",
            translate: "Quản lý phép năm điều chỉnh, bổ sung",
            type: "item",
            url: "/hrms/attendance/business/declareleave",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_attendance_setting",
        title: "Thiết lập",
        translate: "Thiết lập",
        type: "group",
        icon: "gear",
        url: "/hrms/attendance/setting",
        children: [
          {
            id: "timesheet_formula",
            title: "Công thức tính công",
            translate: "Công thức tính công",
            type: "item",
            url: "/hrms/attendance/setting/timesheetformula",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_attendance_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/attendance/list",
        children: [
          {
            id: "symbol",
            title: "Ký hiệu công",
            translate: "Ký hiệu công",
            type: "item",
            url: "/hrms/attendance/list/symbol",
            exactMatch: true, children: [],
          },
          {
            id: "timetype",
            title: "Kiểu công",
            translate: "Kiểu công",
            type: "item",
            url: "/hrms/attendance/list/timetype",
            exactMatch: true, children: [],
          },
          {
            id: "shift",
            title: "Ca làm việc",
            translate: "Ca làm việc",
            type: "item",
            url: "/hrms/attendance/list/shift",
            exactMatch: true, children: [],
          },
          {
            id: "holiday",
            title: "Ngày nghỉ lễ",
            translate: "Ngày nghỉ lễ",
            type: "item",
            url: "/hrms/attendance/list/holiday",
            exactMatch: true, children: [],
          },
          {
            id: "salary_period",
            title: "Kỳ công lương",
            translate: "Kỳ công lương",
            type: "item",
            url: "/hrms/attendance/list/salaryperiod",
            exactMatch: true, children: [],
          },
          {
            id: "terminals",
            title: "Thiết lập máy chấm công",
            translate: "Thiết lập máy chấm công",
            type: "item",
            url: "/hrms/attendance/list/terminals",
            exactMatch: true, children: [],
          },
          {
            id: "otherlist",
            title: "Tham số hệ thống",
            translate: "tham số hệ thống",
            type: "item",
            url: "/hrms/attendance/list/otherlist",
            exactMatch: true, children: [],
          },
        ],
      },
    ],
  },
  {
    id: "cms_payroll",
    title: "Lương",
    translate: "Lương",
    type: "module",
    icon: "pa",
    url: "/hrms/payroll/business/calculatepayroll",
    root: true,
    children: [
      {
        id: "cms_payroll_bus",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/profile/business",
        children: [
          {
            id: "dashboard",
            title: "Dashboard",
            translate: "Dashboard",
            type: "item",
            url: "/hrms/payroll/business/dashboard",
            exactMatch: true, children: [],
          },
          {
            id: "importpayroll",
            title: "Import lương",
            translate: "Import lương",
            type: "item",
            url: "/hrms/payroll/business/importpayroll",
            exactMatch: true, children: [],
          },
          {
            id: "advance",
            title: "Tạm ứng lương",
            translate: "Tạm ứng lương",
            type: "item",
            url: "/hrms/payroll/business/advance",
            exactMatch: true, children: [],
          }/*,
          {
            id: "kpiemployee",
            title: "Tính lương KPI",
            translate: "Tính lương KPI",
            type: "item",
            url: "/hrms/payroll/business/kpiemployee",
            exactMatch: true, children: [],
          }*/,
          {
            id: "payroll_salaryelement",
            title: "Tính lương",
            translate: "Tính lương",
            type: "item",
            url: "/hrms/payroll/business/calculatepayroll",
            exactMatch: true, children: [],
          },
          {
            id: "importtaxincome",
            title: "Import quyết toán thuế",
            translate: "Import quyết toán thuế",
            type: "item",
            url: "/hrms/payroll/business/importtaxincome",
            exactMatch: true, children: [],
          },
          {
            id: "taxincome",
            title: "Quyết toán thuế TNCN",
            translate: "Quyết toán thuế TNCN",
            type: "item",
            url: "/hrms/payroll/business/taxincome",
            exactMatch: true, children: [],
          },

        ],
      },
      {
        id: "cms_payroll_set",
        title: "Thiết lập",
        translate: "Thiết lập",
        type: "group",
        icon: "gear",
        url: "/hrms/profile/setting",
        children: [
          {
            id: "payroll_formula",
            title: "Công thức tính lương",
            translate: "Công thức tính lương",
            type: "item",
            url: "/hrms/payroll/setting/payrollformula",
            exactMatch: true, children: [],
          },
          /*    {
                id: "kpiformula",
                title: "Công thức KPI",
                translate: "Công thức KPI",
                type: "item",
                url: "/hrms/payroll/setting/kpiformula",
                exactMatch: true, children: [],
          },
              {
                id: "kpiposition",
                title: "Thiết lập KPI theo chức vụ",
                translate: "Thiết lập KPI theo chức vụ",
                type: "item",
                url: "/hrms/payroll/setting/kpiposition",
                exactMatch: true, children: [],
          },*/
          {
            id: "paycheck",
            title: "Phiếu lương",
            translate: "Phiếu lương",
            type: "item",
            url: "/hrms/payroll/setting/paycheck",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_payroll_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/payroll/list",
        children: [
          {
            id: "salary_element",
            title: "Phần tử lương",
            translate: "Phần tử lương",
            type: "item",
            url: "/hrms/payroll/list/salaryelement",
            exactMatch: true, children: [],
          },
          {
            id: "salary_structure",
            title: "Thông tin kết cấu bảng lương",
            translate: "Thông tin kết cấu bảng lương",
            type: "item",
            url: "/hrms/payroll/list/salarystructure",
            exactMatch: true, children: [],
          },
          /*    {
                id: "kpigroup",
                title: "Nhóm phần tử KPI",
                translate: "Nhóm phần tử KPI",
                type: "item",
                url: "/hrms/payroll/list/kpigroup",
                exactMatch: true, children: [],
          },
              {
                id: "kpitarget",
                title: "Phần tử KPI",
                translate: "Phần tử KPI",
                type: "item",
                url: "/hrms/payroll/list/kpitarget",
                exactMatch: true, children: [],
          },
              {
                id: "listmachine",
                title: "Danh mục máy uốn",
                translate: "Danh mục máy uốn",
                type: "item",
                url: "/hrms/payroll/list/listmachine",
                exactMatch: true, children: [],
          },
              {
                id: "listproduct",
                title: "Danh mục sản phẩm",
                translate: "Danh mục sản phẩm",
                type: "item",
                url: "/hrms/payroll/list/listproduct",
                exactMatch: true, children: [],
          },*/
        ],
      },
    ],
  },
  {
    id: "smp_mortarboard",
    title: "Nhân tài",
    translate: "Nhân tài",
    type: "module",
    icon: "mortarboard",
    url: "",
    root: true,
    children: [
      {
        id: "cms_app_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/profile/business",
        children: [
          
          {
            id: "searchtalent",
            title: "Tìm kiếm nhân tài",
            translate: "Tìm kiếm nhân tài",
            type: "item",
            url: "/hrms/profile/business/searchtalent",
            exactMatch: true, children: [],
          },
          {
            id: "talentmng",
            title: "Hồ sơ nhân tài",
            translate: "Hồ sơ nhân tài",
            type: "item",
            url: "/hrms/profile/business/talentmng",
            exactMatch: true, children: [],
          },
        ]
      },
      {
        id: "cms_app_talent_setting",
        title: "Thiết lập",
        translate: "Thiết lập",
        type: "group",
        icon: "gear",
        url: "/hrms/profile/business",
        children: [
          {
            id: "talentsetting",
            title: "Thiết lập nhân tài",
            translate: "Thiết lập nhân tài",
            type: "item",
            url: "/hrms/profile/business/talentsetting",
            exactMatch: true, children: [],
          },
          
        ]
      },


    ]
  },

  
  {
    id: "cms_report",
    title: "Báo cáo",
    translate: "Báo cáo",
    type: "module",
    icon: "rpt",
    url: "",
    root: true,
    children: [
      {
        id: "cms_report_bus",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/report/business",
        children: [
          {
            id: "report-management",
            title: "Báo cáo",
            translate: "Báo cáo",
            type: "item",
            url: "/hrms/report/business/businessreport",
            exactMatch: true, children: [],
          },
          {
            id: "report-business",
            title: "Báo cáo quản trị",
            translate: "Báo cáo quản trị",
            type: "item",
            url: "/hrms/report/business/reportchart",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_list",
        title: "Danh mục",
        translate: "Danh mục",
        type: "group",
        icon: "list",
        url: "/hrms/profile/list",
        children: [
          {
            id: "reportconfig",
            title: "Báo cáo",
            translate: "Báo cáo",
            type: "item",
            url: "/hrms/profile/list/reportconfig",
            exactMatch: true,
            children: [],
          },
        ],
      },
      
    ],
  },
  {
    id: "cms_administration",
    title: "Hành chính",
    translate: "Hành chính",
    type: "module",
    icon: "bo",
    url: "/hrms/administration",
    root: true,
    children: [
      {
        id: "cms_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        children: [
          {
            id: "booking",
            title: "Đặt phòng họp",
            translate: "Đặt phòng họp",
            type: "item",
            url: "/hrms/administration/business/booking",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "cms_list",
        title: "Danh mục",
        translate: "Danh mục",
        icon: "list",
        type: "group",
        children: [
          {
            id: "room",
            title: "Phòng họp",
            translate: "Phòng họp",
            type: "item",
            url: "/hrms/administration/list/room",
            exactMatch: true, children: [],
          },
        ],
      },
      
    ],
  },
  {
    id: "cms_internalblog",
    title: "Truyền thông",
    translate: "Truyền thông",
    type: "module",
    icon: "mar",
    url: "/hrms/media/internalblog",
    root: true,
    children: [
      {
        id: "cms_app_business",
        title: "Nghiệp vụ",
        translate: "Nghiệp vụ",
        type: "group",
        icon: "users",
        url: "/hrms/media/business",
        children: [
          
          {
            id: "cms-app-internalblog",
            title: "Tin tức nội bộ",
            translate: "Tin tức nội bộ",
            type: "item",
            url: "/hrms/media/business/internalblog",
            exactMatch: true, children: [],
          },
          {
            id: "cms-app-survey",
            title: "Thông tin cuộc khảo sát",
            translate: "Thông tin cuộc khảo sát",
            type: "item",
            url: "/hrms/media/business/survey",
            exactMatch: true, children: [],
          },
        ]
      },

    ]
  },
  {
    id: "cms_system",
    title: "Hệ thống",
    translate: "Hệ thống",
    type: "module",
    icon: "sys",
    url: "/hrms/system",
    children: [
      {
        id: "cms_system_account",
        title: "Tài khoản",
        translate: "Tài khoản",
        type: "group",
        url: "",
        exactMatch: true,
        children: [
          {
            id: "sys_groupuser",
            title: "Nhóm tài khoản",
            translate: "Nhóm tài khoản",
            type: "item",
            url: "/hrms/system/groupuser",
            exactMatch: true, children: [],
          },
          {
            id: "sys_user",
            title: "Tài khoản",
            translate: "Tài khoản",
            type: "item",
            url: "/hrms/system/user",
            exactMatch: true, children: [],
          },
          {
            id: "sys_groupuser_permission",
            title: "Phân quyền nhóm tài khoản",
            translate: "Phân quyền nhóm tài khoản",
            type: "item",
            url: "/hrms/system/grouppermission",
            exactMatch: true, children: [],
          },
          {
            id: "sys_user_permission",
            title: "Phân quyền Tài khoản",
            translate: "Phân quyền Tài khoản",
            type: "item",
            url: "/hrms/system/userpermission",
            exactMatch: true, children: [],
          },
        ],
      },
      {
        id: "sys_groupuser",
        title: "Thiết lập biểu mẫu",
        translate: "Thiết lập biểu mẫu",
        type: "item",
        url: "/hrms/system/groupuser",
        exactMatch: true,
        children: [

          {
            id: "sys_report",
            title: "Thiết lập biểu mẫu",
            translate: "Thiết lập biểu mẫu",
            type: "item",
            url: "/hrms/system/settingreport",
            exactMatch: true, children: [],
          },
          {
            id: "mailsetting",
            title: "Thiết lập biểu mẫu mail",
            translate: "Thiết lập biểu mẫu mail",
            type: "item",
            url: "/hrms/system/mailsetting",
            exactMatch: true, children: [],
          },
          {
            id: "sys_settingremind",
            title: "Thiết lập hệ thống",
            translate: "Thiết lập hệ thống",
            type: "item",
            url: "/hrms/system/settingremind",
            exactMatch: true, children: [],
          },
          {
            id: "settingmap",
            title: "Thiết lập địa điểm chấm công",
            translate: "Thiết lập địa điểm chấm công",
            type: "item",
            url: "/hrms/system/settingmap",
            exactMatch: true, children: [],
          },
          {
            id: "sys_approveprocess",
            title: "Thiết lập quy trình phê duyệt",
            translate: "Thiết lập quy trình phê duyệt",
            type: "item",
            url: "/hrms/system/approveprocess",
            exactMatch: true, children: [],
          },
          {
            id: "sys_approvetemplate",
            title: "Thiết lập Template phê duyệt",
            translate: "Thiết lập Template phê duyệt",
            type: "item",
            url: "/hrms/system/approvetemplate",
            exactMatch: true,
            children: [],
          },
          {
            id: "sys_approvetemplatesetup",
            title: "Thiết lập Template phê duyệt cho bộ phận",
            translate: "Thiết lập Template phê duyệt cho bộ phận",
            type: "item",
            url: "/hrms/system/approvetemplatesetup",
            exactMatch: true,
            children: [],
          },
          {
            id: "sys_approvetemplatesetupemp",
            title: "Thiết lập Template phê duyệt cho nhân viên",
            translate: "Thiết lập Template phê duyệt cho nhân viên",
            type: "item",
            url: "/hrms/system/approvetemplatesetupemp",
            exactMatch: true,
            children: [],
          },
          {
            id: "sys_reportdynamic",
            title: "Thiết lập báo cáo động",
            translate: "Thiết lập báo cáo động",
            type: "item",
            url: "/hrms/system/reportdynamic",
            exactMatch: true,
            children: [],
          }
        ],
      }
    ],

    root: true,
  },
];

